[package]
name = "wgpu-v2"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
image = { version = "0.25.10", features = ["png", "jpeg"] }
wgpu = "29.0.0"
winit = { version = "0.30.8" }
env_logger = "0.11"
pollster = "0.4"
glam = "0.33.2"
rand = "0.10.1"
